
import json
import numpy as np
import os

def to_q8_8(val):
    return int(val)

def generate_header():
    # Load Parameters
    with open('results/linear_params.json', 'r') as f:
        params = json.load(f)
    print("Loaded params")
    
    weights = params['weights'] # List of 20 ints
    bias = params['bias']       # Int
    
    # Load Test Data
    with open('results/test_data.json', 'r') as f:
        data = json.load(f)
    
    X_test = data['X_test'] # List of lists
    y_test = data['y_test'] # List of ints
    
    num_samples = len(X_test)
    print(f"Generating vectors for {num_samples} samples...")
    
    os.makedirs('testbench', exist_ok=True)
    
    # 1. Generate .mem file for Hex Memory Loading
    # Format: 
    # [Feature 0] [Feature 1] ... [Feature 19] [Expected Decision] [Expected Prediction]
    # All in Hex? Or just create a massive flat array in Verilog?
    # A .mem file with $readmemh is best for large data.
    # We will pack: 20 features + 1 expected_decision + 1 expected_prediction = 22 words per line.
    
    with open('testbench/test_data.mem', 'w') as f:
        for i in range(num_samples):
            features = X_test[i]
            
            # Calculate Expected Result (Python Sim)
            dot_prod = 0
            for w, x in zip(weights, features):
                dot_prod += w * x
            
            bias_shifted = bias << 8
            sum_val = dot_prod + bias_shifted
            decision_q8_8 = sum_val >> 8
            
            # Saturate
            if decision_q8_8 > 32767: decision_q8_8 = 32767
            elif decision_q8_8 < -32768: decision_q8_8 = -32768
            
            prediction = 1 if decision_q8_8 >= 0 else 0
            
            # Write to .mem (Hex format)
            # 16-bit hex values. Handle negatives via 2's complement mask & 0xFFFF
            line_parts = []
            for feat in features:
                line_parts.append(f"{feat & 0xFFFF:04x}")
            
            line_parts.append(f"{decision_q8_8 & 0xFFFF:04x}")
            line_parts.append(f"{prediction & 0xFFFF:04x}")
            
            f.write(" ".join(line_parts) + "\n")
            
    print(f"Wrote {num_samples} vectors to testbench/test_data.mem")

    # 2. Update Header with Weights and Count
    with open('testbench/svm_test_vectors.vh', 'w') as f:
        f.write("// Auto-generated by generate_test_vectors.py\n")
        f.write(f"parameter NUM_TEST_CASES = {num_samples};\n")
        f.write(f"parameter signed [15:0] TEST_BIAS = {bias};\n\n")
        
        # Weights
        f.write("reg signed [15:0] TEST_WEIGHTS [0:19];\n")
        f.write("initial begin\n")
        for i, w in enumerate(weights):
            f.write(f"    TEST_WEIGHTS[{i}] = {w};\n")
        f.write("end\n")

if __name__ == "__main__":
    generate_header()
